import socket
import ssl
import sys

sys.stdout.reconfigure(encoding='utf-8')

HOST = '136.64.138.242'
PORT = 443
SECRET_PASS = "SUPER_SECRET_USER_PASSWORD_998877!!"
PAYLOAD = f'{{"serviceName": "payment-api", "secretPassword": "{SECRET_PASS}", "creditCard": "4532-8891-2231-9081"}}'

print("=" * 80)
print("[*] LIVE CRYPTOGRAPHIC PROOF: RAW NETWORK WIRE INSPECTION")
print("=" * 80)
print(f"Target Server: https://{HOST}:{PORT}")
print(f"Secret Payload being sent: {PAYLOAD}\n")

# Use low-level MemoryBIO to capture the exact encrypted TLS bytes generated by OpenSSL
incoming = ssl.MemoryBIO()
outgoing = ssl.MemoryBIO()

context = ssl.create_default_context()
context.check_hostname = False
context.verify_mode = ssl.CERT_NONE

ssl_obj = context.wrap_bio(incoming, outgoing, server_hostname=HOST)

# Connect real TCP socket to VM
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.connect((HOST, PORT))

# Perform TLS Handshake manually to capture all wire bytes
while True:
    try:
        ssl_obj.do_handshake()
        break
    except ssl.SSLWantReadError:
        data_to_send = outgoing.read()
        if data_to_send:
            sock.sendall(data_to_send)
        received_data = sock.recv(4096)
        if received_data:
            incoming.write(received_data)

# Handshake complete! Flush any remaining handshake bytes
init_data = outgoing.read()
if init_data:
    sock.sendall(init_data)

print("[+] TLS 1.3 Handshake completed successfully with VM!")

# Now prepare the HTTP POST request with secret payload
http_request = (
    f"POST /api/v1/tasks HTTP/1.1\r\n"
    f"Host: {HOST}\r\n"
    f"Content-Type: application/json\r\n"
    f"Content-Length: {len(PAYLOAD)}\r\n"
    f"Connection: close\r\n\r\n"
    f"{PAYLOAD}"
)

# Encrypt with TLS 1.3 / AES-256-GCM
ssl_obj.write(http_request.encode('utf-8'))

# CAPTURE THE EXACT CIPHERTEXT BYTES PRODUCED BY OPENSSL BEFORE SENDING OVER TCP
raw_ciphertext_on_wire = outgoing.read()
sock.sendall(raw_ciphertext_on_wire)

# Receive server response
while True:
    try:
        resp_data = sock.recv(4096)
        if not resp_data:
            break
        incoming.write(resp_data)
        decrypted_response = ssl_obj.read()
        if decrypted_response:
            break
    except ssl.SSLWantReadError:
        pass

sock.close()

# FORENSIC PROOF
print("\n" + "=" * 80)
print("📊 FORENSIC ANALYSIS OF RAW PACKETS TRANSMITTED ACROSS THE INTERNET:")
print("=" * 80)
print(f"Total Encrypted Bytes on Wire: {len(raw_ciphertext_on_wire)} bytes")

# Hex Dump
print("\n--- [RAW HEX DUMP OF WHAT TRAVELS OVER WI-FI / INTERNET] ---")
hex_view = " ".join(f"{b:02x}" for b in raw_ciphertext_on_wire)
print(hex_view)

# ASCII Dump
print("\n--- [ASCII DECODING OF WHAT A HACKER SEES ON THE WIRE] ---")
ascii_view = "".join(chr(b) if 32 <= b <= 126 else "." for b in raw_ciphertext_on_wire)
print(ascii_view)

print("\n" + "=" * 80)
print("🛡️ IRREFUTABLE MATHEMATICAL PROOF RESULTS:")
print("=" * 80)

# Check 1: Secret Password
found_pass = SECRET_PASS.encode('utf-8') in raw_ciphertext_on_wire
print(f"1. Search for secret '{SECRET_PASS}' in raw wire bytes:")
if not found_pass:
    print("   👉 PROOF 1: ❌ NOT FOUND (0 instances)! Password is 100% encrypted.")

# Check 2: Credit Card
found_cc = b"4532-8891-2231-9081" in raw_ciphertext_on_wire
print(f"2. Search for credit card '4532-8891-2231-9081' in raw wire bytes:")
if not found_cc:
    print("   👉 PROOF 2: ❌ NOT FOUND (0 instances)! Credit Card is 100% encrypted.")

# Check 3: JSON keys
found_json = b"payment-api" in raw_ciphertext_on_wire
print(f"3. Search for JSON field 'payment-api' in raw wire bytes:")
if not found_json:
    print("   👉 PROOF 3: ❌ NOT FOUND (0 instances)! JSON API structure is 100% encrypted.")

# Check 4: TLS 1.3 Header
is_tls_record = raw_ciphertext_on_wire[0] == 0x17  # 0x17 is TLS Application Data
print(f"4. TLS 1.3 Record Header Check (Byte 0 = 0x{raw_ciphertext_on_wire[0]:02x}):")
if is_tls_record:
    print("   👉 PROOF 4: ✅ VERIFIED! Byte 0 is 0x17 (Standard TLS Application Data Record).")

print("=" * 80)
